import type { NextPage } from "next";
import Head from "next/head";
import {
  AuthenticatedTemplate,
  UnauthenticatedTemplate,
} from "@azure/msal-react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container p-8">
        <div>
          <Link href="/page-1">
            <span className="font-bold text-blue-500 cursor-pointer">
              got to page 1
            </span>
          </Link>
        </div>
        <AuthenticatedTemplate>
          <p className="text-2xl">Authenticated</p>
          <p>
            Inside AuthenticatedTemplate will not render after comming back from
            page-1
          </p>
        </AuthenticatedTemplate>

        <UnauthenticatedTemplate>
          <h1 className="text-2xl">Unauthenticated</h1>
          <p>
            Inside UnauthenticatedTemplate will not render after comming back
            from page-1
          </p>
        </UnauthenticatedTemplate>
      </main>
    </div>
  );
};

export default Home;
